# -*- coding: utf-8 -*-
# Clop 快速汉化 · 第 1 批(SwiftUI 调用点,列表前半)
# key/value 都是含引号的 Swift 字符串原文,原文中的反斜杠转义原样保留
T1 = {
    r'" Enable **\(fileType == .pdf ? "PDF" : fileType.rawValue)** auto-optimiser"': r'" 启用 **\(fileType == .pdf ? "PDF" : fileType.rawValue)** 自动优化"',
    r'" Enable clipboard optimiser"': r'" 启用剪贴板自动优化"',
    r'"1 day"': r'"1 天"',
    r'"1 hour"': r'"1 小时"',
    r'"1 minute"': r'"1 分钟"',
    r'"1 month"': r'"1 个月"',
    r'"1 seconds"': r'"1 秒"',
    r'"1 week"': r'"1 周"',
    r'"1/2 of source"': r'"原片的 1/2"',
    r'"1/4 of source"': r'"原片的 1/4"',
    r'"10 minutes"': r'"10 分钟"',
    r'"10 seconds"': r'"10 秒"',
    r'"12 hours"': r'"12 小时"',
    r'"15 seconds"': r'"15 秒"',
    r'"2 minutes"': r'"2 分钟"',
    r'"2 seconds"': r'"2 秒"',
    r'"3 days"': r'"3 天"',
    r'"3 seconds"': r'"3 秒"',
    r'"30 minutes"': r'"30 分钟"',
    r'"30 seconds"': r'"30 秒"',
    r'"4 seconds"': r'"4 秒"',
    r'"5 minutes"': r'"5 分钟"',
    r'"5 seconds"': r'"5 秒"',
    r'"60 seconds"': r'"60 秒"',
    r'"ASPECT RATIOS"': r'"宽高比"',
    r'"About..."': r'"关于…"',
    r'"Accumulate optimised images in clipboard"': r'"在剪贴板中累积优化后的图像"',
    r'"Action buttons"': r'"操作按钮"',
    r'"Actions for the selection"': r'"针对所选项目的操作"',
    r'"Actions"': r'"操作"',
    r'"Adaptive (best size and quality)"': r'"自适应(体积与画质最佳)"',
    r'"Adaptive"': r'"自适应"',
    r'"Add action"': r'"添加操作"',
    r'"Add app"': r'"添加应用"',
    r'"Add folder"': r'"添加文件夹"',
    r'"Add pipeline"': r'"添加管线"',
    r'"Add to Atoll"': r'"添加到 Atoll"',
    r'"Add to Dockside"': r'"添加到 Dockside"',
    r'"Add to Dropover"': r'"添加到 Dropover"',
    r'"Add to Yoink"': r'"添加到 Yoink"',
    r'"Add to shelf\u{2026}"': r'"添加到暂存区…"',
    r'"Add to"': r'"添加到"',
    r'"Advanced"': r'"高级"',
    r'"Aggressive optimisation"': r'"激进优化"',
    r'"All types"': r'"所有类型"',
    r'"Allow agents to write arbitrary scripts in pipelines"': r'"允许智能体在管线中写入任意脚本"',
    r'"Always use compact layout"': r'"始终使用紧凑布局"',
    r'"Any type"': r'"任意类型"',
    r'"Apply to all"': r'"应用到全部"',
    r'"Apply to selection"': r'"应用到所选"',
    r'"Aspect ratio locked, click to unlock"': r'"宽高比已锁定,点按解锁"',
    r'"Aspect ratio"': r'"宽高比"',
    r'"Assign existing pipeline"': r'"指派现有管线"',
    r'"Assign to a button"': r'"指定到按钮"',
    r'"Assigned to \(assignmentHelp(assignment)). Click to go there or remove."': r'"已指定到 \(assignmentHelp(assignment))。点按前往或移除。"',
    r'"Audio files"': r'"音频文件"',
    r'"Audio"': r'"音频"',
    r'"Auto Copy optimised files to clipboard"': r'"自动将优化后的文件复制到剪贴板"',
    r'"Auto clear all after"': r'"全部清空时间"',
    r'"Auto hide"': r'"自动隐藏"',
    r'"Auto"': r'"自动"',
    r'"Auto-conversion behaviour for compatible formats"': r'"兼容格式的自动转换行为"',
    r'"Automation"': r'"自动化"',
    r'"Automations"': r'"自动化"',
    r'"Backups deleted, re-running unavailable"': r'"备份已删除,无法重新运行"',
    r'"Backups"': r'"备份"',
    r'"Batch optimiser"': r'"批量优化器"',
    r'"Best for photos and illustrations"': r'"适合照片和插画"',
    r'"Best for text and low-detail images"': r'"适合文字和低细节图像"',
    r'"Better quality"': r'"更佳画质"',
    r'"Bitrate: \(bitrate) kbps"': r'"码率:\(bitrate) kbps"',
    r'"Bottom left"': r'"左下"',
    r'"Bottom right"': r'"右下"',
    r'"Bring back default sizes"': r'"恢复默认尺寸"',
    r'"Bring back last result"': r'"找回上个结果"',
    r'"Built-in"': r'"内置"',
    r'"CLI installed at \(CLOP_CLI_BIN_SHELL)"': r'"命令行工具已安装到 \(CLOP_CLI_BIN_SHELL)"',
    r'"Cancel"': r'"取消"',
    r'"Cap frames per second to"': r'"帧率上限设为"',
    r'"Cap frames per second"': r'"限制帧率"',
    r'"Change bitrate"': r'"更改码率"',
    r'"Change expiration"': r'"更改有效期"',
    r'"Change format by"': r'"切换格式的方式"',
    r'"Change playback speed"': r'"更改播放速度"',
    r'"Choose app…"': r'"选择应用…"',
    r'"Choose the video frame used for the crop preview"': r'"选择用于裁剪预览的视频帧"',
    r'"Clear all"': r'"全部清空"',
    r'"Clear search"': r'"清除搜索"',
    r'"Clear selection"': r'"取消选择"',
    r'"Click to edit"': r'"点按编辑"',
    r'"Click to rename"': r'"点按重命名"',
    r'"Clipboard actions"': r'"剪贴板操作"',
    r'"Clop will automatically pick between JPEG or PNG conversion based on image entropy, and choose a fitting compression factor adaptively"': r'"Clop 会根据图像信息量自动在 JPEG 和 PNG 之间选择,并自适应地选取合适的压缩系数"',
    r'"Compact"': r'"紧凑"',
    r'"Compare before / after"': r'"对比原图 / 成品"',
    r'"Comparison"': r'"对比"',
    r'"Compatibility"': r'"兼容性"',
    r'"Compression factor"': r'"压缩系数"',
    r'"Compression"': r'"压缩"',
    r'"Configured in"': r'"配置于"',
    r'"Contact the developer"': r'"联系开发者"',
    r'"Convert HDR to SDR"': r'"将 HDR 转换为 SDR"',
    r'"Convert audio to AAC"': r'"将音频转换为 AAC"',
    "\"Convert detail heavy images to JPEG and low-detail ones to PNG, ignoring the compression factor's format\"": "\"细节丰富的图像转为 JPEG、低细节的转为 PNG,忽略压缩系数所指的格式\"",
    r'"Convert to "': r'"转换为 "',
    r'"Convert to GIF"': r'"转换为 GIF"',
    r'"Convert to another format"': r'"转换为其他格式"',
    r'"Convert to image"': r'"转换为图像"',
    r'"Convert to"': r'"转换为"',
    r'"Convert to…"': r'"转换为…"',
    r'"Converts:"': r'"转换为:"',
    r'"Copies the line"': r'"复制该行"',
    r'"Copy Download Link"': r'"复制下载链接"',
    r'"Copy Path"': r'"复制路径"',
    r'"Copy Room Link"': r'"复制房间链接"',
    r'"Copy all links"': r'"复制全部链接"',
    r'"Copy all send links"': r'"复制全部发送链接"',
    r'"Copy deep link"': r'"复制深链"',
    r'"Copy image paths"': r'"复制图像路径"',
    r'"Copy link · expires in \(expirationShortLabel(optimiser.sendExpiration))"': r'"复制链接 · \(expirationShortLabel(optimiser.sendExpiration))后过期"',
    r'"Copy link"': r'"复制链接"',
    r'"Copy send link"': r'"复制发送链接"',
    r'"Copy to clipboard"': r'"复制到剪贴板"',
    r'"Copy"': r'"复制"',
    r'"Cover art is kept only for formats that can store it (AAC, MP3, FLAC); it is dropped for others."': r'"仅 AAC、MP3、FLAC 等可存储封面的格式会保留封面图,其余格式会丢弃。"',
    r'"Cover art"': r'"封面图"',
    r'"Cover size"': r'"封面尺寸"',
    r'"Create debug dump"': r'"生成调试信息"',
    r'"Create new \(typeLabel(type)) pipeline"': r'"新建\(typeLabel(type))管线"',
    r'"Crop all images to a landscape orientation."': r'"将所有图像裁剪为横向。"',
    r'"Crop all images to a portrait orientation."': r'"将所有图像裁剪为纵向。"',
    r'"Crop all images to the specified size while keeping the original orientation of each image."': r'"将所有图像裁剪到指定尺寸,并保留各自原始方向。"',
    r'"Crop all pages to the specified size while keeping the original orientation of each page."': r'"将所有页面裁剪到指定尺寸,并保留各自原始方向。"',
    r'"Crop and resize to \(sizeStr)"': r'"裁剪并缩放到 \(sizeStr)"',
    r'"Crop and resize..."': r'"裁剪并缩放…"',
    r'"Crop the \(optimiser.type.str) to a landscape orientation."': r'"将\(optimiser.type.str)裁剪为横向。"',
    r'"Crop the \(optimiser.type.str) to a portrait orientation."': r'"将\(optimiser.type.str)裁剪为纵向。"',
    r'"Crop"': r'"裁剪"',
    r'"Custom name template"': r'"自定义命名模板"',
    r'"Delete backups"': r'"删除备份"',
    r'"Delete pipeline"': r'"删除管线"',
    r'"Delete preset"': r'"删除预设"',
    r'"Delete the backups for this batch?"': r'"删除此批次的备份?"',
    r'"Dimensions: \(size.s)"': r'"尺寸:\(size.s)"',
    r'"Dismiss result after"': r'"结果消失时间"',
    r'"Done"': r'"完成"',
    r'"Downloaded \(session.downloadCount) time\(session.downloadCount == 1 ? "" : "s")"': r'"已下载 \(session.downloadCount) 次"',
    r'"Downscale HiDPI images to 72 DPI"': r'"将 HiDPI 图像降采样到 72 DPI"',
    r'"Downscale cover art to"': r'"封面图缩小到"',
    r'"Downscale cover art"': r'"缩小封面图"',
    r'"Downscale resolution to"': r'"分辨率降低到"',
    r'"Downscale to"': r'"缩小到"',
    r'"Downscale"': r'"缩小"',
    r'"Drag across the preview to move the split divider"': r'"在预览上拖动以移动分割线"',
    r'"Drag files into the **drop zone** at\nthe **bottom right** corner of your screen"': r'"把文件拖到屏幕**右下角**的**投放区**"',
    r'"Drag files onto the drop zone\nto optimise them"': r'"把文件拖到投放区即可优化"',
    r'"Drag toward Better quality for better-looking video, toward Smaller size for a smaller file"': r'"向「更佳画质」拖动画质更好,向「更小体积」拖动文件更小"',
    r'"Drop files and folders here"': r'"把文件和文件夹拖到这里"',
    r'"Drop frames (smaller file)"': r'"丢帧(文件更小)"',
    r'"Drop to optimise"': r'"拖入即优化"',
    r'"Drops & Results"': r'"投放与结果"',
    r'"Edit pipeline"': r'"编辑管线"',
    r'"Edit with \(appDisplayName(appURL))"': r'"用 \(appDisplayName(appURL)) 编辑"',
    r'"Enable MCP"': r'"启用 MCP"',
    r'"Enable clipboard optimiser"': r'"启用剪贴板优化器"',
    r'"Enable drop zone"': r'"启用投放区"',
    r'"Encoder"': r'"编码器"',
    r'"Example:"': r'"示例:"',
    r'"Expire Trial"': r'"终止试用期"',
    r'"Extend instead of clipping"': r'"扩展而非裁切"',
    r'"Extract cover art"': r'"提取封面图"',
    r'"Extract pages as images"': r'"将页面导出为图像"',
    r'"File handling"': r'"文件处理"',
    r'"File name template"': r'"文件名模板"',
    r'"File types"': r'"文件类型"',
    r'"File"': r'"文件"',
    r'"Fit under size"': r'"压到指定体积"',
    r'"Folder template"': r'"文件夹模板"',
    r'"Folders"': r'"文件夹"',
    r'"Follow the cursor across screens"': r'"跟随光标跨屏幕移动"',
    r'"Follows the standard .gitignore rules."': r'"遵循标准 .gitignore 规则。"',
    r'"Force clean working directory"': r'"强制清空工作目录"',
    r'"Format"': r'"格式"',
    r'"Frame rate"': r'"帧率"',
    r'"Frame"': r'"帧"',
    r'"Full"': r'"完整"',
    r'"GIF frame dropping"': r'"GIF 丢帧"',
    r'"Get Clop Pro"': r'"获取 Clop Pro"',
    r'"Go to pipeline"': r'"前往管线"',
    r'"Go to"': r'"前往"',
    r'"Grows pages with empty paper instead of cutting content away. Useful for fitting a book page on a phone screen without losing text at the edges."': r'"页面放不下时扩展纸张而不是裁掉内容。适合把书页适配到手机屏幕且不丢失边缘文字。"',
    r'"HEIC and AVIF data"': r'"HEIC 与 AVIF 数据"',
    r'"Height"': r'"高度"',
    r'"Hide button tooltips"': r'"隐藏按钮提示"',
    r'"Hide tooltip"': r'"隐藏提示"',
    r'"Hold **⌘ Command** to zoom in, add **⌥ Option** to zoom further"': r'"按住 **⌘ Command** 放大,再加按 **⌥ Option** 继续放大"',
    r'"Hold the trigger keys and"': r'"按住触发键并"',
    r'"Hold"': r'"按住"',
    r'"Icon"': r'"图标"',
    r'"Ignore clipboard events from \(appName)"': r'"忽略来自 \(appName) 的剪贴板事件"',
    r'"Ignore images with extension"': r'"忽略这些扩展名的图像"',
    r'"Ignore rules"': r'"忽略规则"',
    r'"Ignore videos with extension"': r'"忽略这些扩展名的视频"',
    r'"Image data"': r'"图像数据"',
    r'"Image files"': r'"图像文件"',
    r'"Image"': r'"图像"',
    r'"Images"': r'"图像"',
    r'"Images, videos, PDFs and audio are added; everything else is ignored. Drop more anytime to keep adding."': r'"图像、视频、PDF 和音频会被加入,其余忽略。可随时继续拖入更多文件。"',
    r'"In place (replace original)"': r'"原位(替换原件)"',
    r'"In place"': r'"原位"',
    r'"Install command-line integration"': r'"安装命令行集成"',
    r'"Install"': r'"安装"',
    r'"Keep all clipboard results"': r'"保留全部剪贴板结果"',
    r'"Keep duration (choppier motion)"': r'"保持时长(动作更卡顿)"',
    r'"Keep frames (smoother, higher fps)"': r'"保留帧(更流畅,帧率更高)"',
    r'"Landscape"': r'"横向"',
    r'"Last focused: \(appName)"': r'"上次聚焦:\(appName)"',
    r'"Launch at login"': r'"登录时启动"',
    r'"Layout"': r'"布局"',
    r'"License: \(proactive ? "Pro" : "Free")"': r'"许可:\(proactive ? "Pro" : "Free")"',
    r'"Link expiration"': r'"链接有效期"',
    r'"Link expires in \(expirationDurationLabel(optimiser.sendExpiration))"': r'"链接 \(expirationDurationLabel(optimiser.sendExpiration))后过期"',
    r'"Loading installed apps…"': r'"正在载入已安装的应用…"',
    r'"Long edge"': r'"长边"',
    r'"Lossless"': r'"无损"',
    r'"Loudness"': r'"响度"',
    r'"Manage Licence"': r'"管理许可"',
    r'"Manage license"': r'"管理许可"',
    r'"Manual conversion behaviour"': r'"手动转换行为"',
    r'"Menubar icon"': r'"菜单栏图标"',
    r'"Missing"': r'"失效"',
}
