# -*- coding: utf-8 -*-
# Clop 快速汉化 · 第 2 批(SwiftUI 调用点,列表后半)
# raw 字符串中单个反斜杠即源文件中的字面反斜杠(如 \( 插值、\n 换行转义)
T2 = {
    r'"Move this pipeline to another file type"': r'"将此管线移到其他文件类型"',
    r'"Move to another file type"': r'"移到其他文件类型"',
    r'"Move to"': r'"移到"',
    r'"Name"': r'"名称"',
    r'"Needs Clop Pro"': r'"需要 Clop Pro"',
    r'"Never expire"': r'"永不过期"',
    r'"Never show this again"': r'"不再显示"',
    r'"Never"': r'"从不"',
    r'"New pipeline"': r'"新建管线"',
    r'"Next page"': r'"下一页"',
    r'"No apps ignored. Clipboard events from all apps are processed."': r'"没有忽略任何应用。所有应用的剪贴板事件都会被处理。"',
    r'"No automations yet. Turn on Clipboard or Drop zone above, or watch a folder, to run pipelines automatically."': r'"还没有自动化。开启上方「剪贴板」或「投放区」,或监视文件夹,即可自动运行管线。"',
    r'"No pipelines yet"': r'"还没有管线"',
    r'"No saved pipelines"': r'"没有已保存的管线"',
    r'"No selection"': r'"未选择"',
    r'"No tool output captured for this failure."': r'"没有捕获到此次失败的工具输出。"',
    r'"Normalise loudness"': r'"响度标准化"',
    r'"Nothing matches \"\(svm.searchQuery)\""': r'"没有与「\(svm.searchQuery)」匹配的内容"',
    r'"Only one side plays at a time, scrub either side to set where both start"': r'"一次只播放一侧,拖动任一侧设定两者起点"',
    r'"Open Room"': r'"打开 Room"',
    r'"Open backups folder"': r'"打开备份文件夹"',
    r'"Open folder with pages"': r'"打开页面所在文件夹"',
    r'"Open the Preset Zones tab to set up per-target drop pipelines"': r'"打开「预设区」标签页,为不同投放目标配置管线"',
    r'"Open the crop and resize window"': r'"打开裁剪缩放窗口"',
    r'"Open with \(appDisplayName(defaultApp))"': r'"用 \(appDisplayName(defaultApp)) 打开"',
    r'"Open with default app"': r'"用默认应用打开"',
    r'"Open with..."': r'"用其他应用打开…"',
    r'"Open working directory"': r'"打开工作目录"',
    r'"Open"': r'"打开"',
    r'"Optimise (aggressive)"': r'"优化(激进)"',
    r'"Optimise images copied from Photos.app"': r'"优化从「照片」应用拷贝的图像"',
    r'"Optimise"': r'"优化"',
    r'"Optimised file placement"': r'"优化后文件的存放位置"',
    r'"Optimised"': r'"已优化"',
    r'"Orientation"': r'"方向"',
    r'"Original"': r'"原件"',
    r'"PDF files"': r'"PDF 文件"',
    r'"Page \(pageIndex + 1) of \(pageCount)"': r'"第 \(pageIndex + 1) 页,共 \(pageCount) 页"',
    r'"Page \(pdfPage.i)/\(pdf.pageCount)"': r'"第 \(pdfPage.i)/\(pdf.pageCount) 页"',
    r'"Page"': r'"页"',
    r'"Pass file through Shortcut"': r'"通过快捷指令处理文件"',
    r'"Pass file through pipeline"': r'"通过管线处理文件"',
    r'"Path"': r'"路径"',
    r'"Pause automatic optimisations"': r'"暂停自动优化"',
    r'"Periodically cleanup files older than"': r'"定期清理早于此时间的文件"',
    r'"Pipeline"': r'"管线"',
    r'"Pipelines"': r'"管线"',
    r'"Play faster"': r'"加速播放"',
    r'"Playback slow down"': r'"播放减速"',
    r'"Playback speed change"': r'"播放速度调整"',
    r'"Playback speed up"': r'"播放加速"',
    r'"Portrait"': r'"纵向"',
    r'"Position on screen"': r'"屏幕位置"',
    r'"Possible actions"': r'"可用操作"',
    r'"Preserve color profile metadata"': r'"保留色彩配置元数据"',
    r'"Preserve file creation and modification dates"': r'"保留文件的创建与修改时间"',
    r'"Preset zone"': r'"预设区"',
    r'"Press ⌘⏎ to crop"': r'"按 ⌘⏎ 裁剪"',
    r'"Previous page"': r'"上一页"',
    r'"Privacy policy"': r'"隐私政策"',
    r'"Quit"': r'"退出"',
    r'"Re-optimisation loop detection window"': r'"重复优化检测窗口"',
    r'"Re-optimise with encoder"': r'"用编码器重新优化"',
    r'"Remove audio on optimised videos"': r'"移除优化后视频的音轨"',
    r'"Remove audio"': r'"移除音轨"',
    r'"Remove from batch"': r'"从批次中移除"',
    r'"Remove from buttons"': r'"从按钮中移除"',
    r'"Remove from ignore list"': r'"从忽略列表移除"',
    r'"Remove from zone"': r'"从投放区移除"',
    r'"Remove this pipeline"': r'"移除此管线"',
    r'"Remove"': r'"移除"',
    r'"Replace with"': r'"替换为"',
    r'"Replay"': r'"重播"',
    r'"Require pressing ⌥ Option to show drop zone"': r'"需要按住 ⌥ Option 才显示投放区"',
    r'"Reset Trial"': r'"重置试用期"',
    r'"Reset after"': r'"重置时间"',
    r'"Reset to default"': r'"恢复默认"',
    r'"Reset"': r'"重置"',
    r'"Resize images until the height is equal or lower than the specified size."': r'"缩放图像直到高度不大于指定值。"',
    r'"Resize images until the longest edge is equal or lower than the specified size."': r'"缩放图像直到最长边不大于指定值。"',
    r'"Resize images until the width is equal or lower than the specified size."': r'"缩放图像直到宽度不大于指定值。"',
    r'"Resolution"': r'"分辨率"',
    r'"Restore normal playback speed (1x)"': r'"恢复正常播放速度(1x)"',
    r'"Restore original size (100%)"': r'"恢复原始尺寸(100%)"',
    r'"Restore original size (\(downscaleFactorLabel(1)))"': r'"恢复原始尺寸(\(downscaleFactorLabel(1)))"',
    r'"Restore original"': r'"恢复原件"',
    r'"Restore original\(ids.count > 1 ? "s" : "")"': r'"恢复原件"',
    r'"Restore originals"': r'"恢复原件"',
    r'"Result: "': r'"结果:"',
    r'"Revert last optimisations"': r'"撤销上次优化"',
    r'"Run this pipeline automatically on the clipboard, drop zone or a watched folder"': r'"在剪贴板、投放区或被监视的文件夹上自动运行此管线"',
    r'"SIZE PRESETS"': r'"尺寸预设"',
    r'"Same folder as original"': r'"与原件同文件夹"',
    r'"Save \(pixelWidth.s)×\(pixelHeight.s) as…"': r'"将 \(pixelWidth.s)×\(pixelHeight.s) 存为…"',
    r'"Save a pipeline in Settings > Automation"': r'"在 设置 > 自动化 中保存管线"',
    r'"Save all to folder"': r'"全部存储到文件夹"',
    r'"Save as..."': r'"存储为…"',
    r'"Save to"': r'"存储到"',
    r'"Search settings"': r'"搜索设置"',
    r'"Secure send link"': r'"安全发送链接"',
    r'"Secure send links expire after"': r'"安全发送链接有效期"',
    r'"See more"': r'"查看更多"',
    r'"Select a single path to edit its "': r'"选择单个路径以编辑其 "',
    r'"Select all"': r'"全选"',
    r'"Select"': r'"选择"',
    r'"Send file securely"': r'"安全发送文件"',
    r'"Send files securely"': r'"安全发送文件"',
    r'"Send with AirDrop"': r'"用隔空投送发送"',
    r'"Sending files (\(wdm.sessions.count))"': r'"正在发送文件(\(wdm.sessions.count))"',
    r'"Settings"': r'"设置"',
    r'"Share"': r'"共享"',
    r'"Shipped with Clop. Delete to hide it; it returns only with a future built-in update."': r'"随 Clop 内置。删除即隐藏,仅在未来内置更新时恢复。"',
    r'"Shortcuts & Automation"': r'"快捷指令与自动化"',
    r'"Show Clop UI in screenshots"': r'"截屏时显示 Clop 界面"',
    r'"Show Copy all / Clear all buttons"': r'"显示「全部复制 / 全部清空」按钮"',
    r'"Show backups in Finder"': r'"在访达中显示备份"',
    r'"Show file"': r'"显示文件"',
    r'"Show floating results"': r'"显示悬浮结果"',
    r'"Show images"': r'"显示图像"',
    r'"Show in Finder"': r'"在访达中显示"',
    r'"Show preset zones by holding or tapping the **⌃ Control** key"': r'"按住或点按 **⌃ Control** 键显示预设区"',
    r'"Show the floating thumbnail and progress when files in this folder are optimised"': r'"优化此文件夹中的文件时显示悬浮缩略图与进度"',
    r'"Side by side comparison"': r'"并排对比"',
    r'"Size: \(bytes.humanSize)"': r'"大小:\(bytes.humanSize)"',
    r'"Skip rules preview"': r'"跳过规则预览"',
    r'"Skipped items because of free version limits"': r'"因免费版限制而跳过的项目"',
    r'"Smaller size"': r'"更小体积"',
    r'"Specific folder"': r'"指定文件夹"',
    r'"Split comparison with a draggable divider"': r'"带可拖动分割线的分屏对比"',
    r'"Square if landscape"': r'"横向时取方形"',
    r'"Square"': r'"方形"',
    r'"Start using Clop"': r'"开始使用 Clop"',
    r'"Stop Transfer"': r'"停止传输"',
    r'"Stop all running optimisations and dismiss all results (\(keyComboModifiers.str) esc)"': r'"停止所有优化并关闭全部结果(\(keyComboModifiers.str) esc)"',
    r'"Stop all"': r'"全部停止"',
    r'"Stop sending"': r'"停止发送"',
    r'"Strip EXIF Metadata"': r'"去除 EXIF 元数据"',
    r'"Strip EXIF metadata"': r'"去除 EXIF 元数据"',
    r'"Suggestions"': r'"建议"',
    r'"Support"': r'"支持"',
    r'"Switch to batch mode when dropping more than"': r'"拖入超过此数量时切换为批量模式"',
    r'"Sync settings with other Macs via iCloud"': r'"通过 iCloud 在多台 Mac 间同步设置"',
    r'"TIFF data"': r'"TIFF 数据"',
    r'"Tap a button to change it"': r'"点按按钮进行修改"',
    r'"Tap"': r'"点按"',
    r'"Target size"': r'"目标尺寸"',
    r'"Template variables"': r'"模板变量"',
    r'"Temporary folder"': r'"临时文件夹"',
    r'"The encoder will choose the best compression factor based on the video contents"': r'"编码器将根据视频内容选择最佳压缩系数"',
    r'"The format bar shows all convertible formats as one-click segments at the bottom of the result; the extension chip pops the formats up on hover"': r'"格式栏把所有可转换格式作为一键分段显示在结果底部;扩展名标签悬停时弹出格式列表"',
    r'"The saved pipeline this refers to was deleted. Remove this entry or re-create the pipeline in the Pipelines tab."': r'"所引用的管线已被删除。移除此项,或在「管线」标签页重新创建。"',
    r'"To folder…"': r'"到文件夹…"',
    r'"To remove an icon, click on it"': r'"点按图标即可移除"',
    r'"Top left"': r'"左上"',
    r'"Top right"': r'"右上"',
    r'"Transform"': r'"变换"',
    r'"Uncrop to \(originalSize.s)"': r'"还原裁剪至 \(originalSize.s)"',
    r'"Upload with Dropshare"': r'"用 Dropshare 上传"',
    r'"Use Preset Zones"': r'"使用预设区"',
    r'"Use batch mode for large drops"': r'"大量拖入时使用批量模式"',
    r'"Version: v\(Bundle.main.version)"': r'"版本:v\(Bundle.main.version)"',
    r'"Video files"': r'"视频文件"',
    r'"Video"': r'"视频"',
    r'"Videos"': r'"视频"',
    r'"Want different pipelines for specific drop targets?"': r'"想为不同投放目标使用不同管线?"',
    r'"Where files go is set in"': r'"文件去向设置于"',
    r'"Width"': r'"宽度"',
    r'"Working directory"': r'"工作目录"',
    r'"\(SwiftUI.Image(systemName: "arrowtriangle.down.square")) Click for more info"': r'"\(SwiftUI.Image(systemName: "arrowtriangle.down.square")) 点按查看详情"',
    r'"\(a.done) done\(a.failed > 0 ? ", \(a.failed) failed" : "")"': r'"完成 \(a.done)\(a.failed > 0 ? ",失败 \(a.failed)" : "")"',
    r'"\(failures.count) file\(failures.count == 1 ? "" : "s") failed"': r'"\(failures.count) 个文件失败"',
    r'"\(manager.items.count) file\(manager.items.count == 1 ? "" : "s")"': r'"\(manager.items.count) 个文件"',
    r'"\(width)px max width @ \(fps)fps\(fps == 20 && width == 800 ? " (recommended)" : "")"': r'"最大宽度 \(width)px @ \(fps)fps\(fps == 20 && width == 800 ? "(推荐)" : "")"',
    r'"\nAllow agents to control Clop, run file optimisations, change settings, write pipelines"': r'"\n允许智能体控制 Clop、执行文件优化、修改设置、编写管线"',
    r'"\nAllows dragging files, paths and URLs to a global drop zone for optimisation"': r'"\n允许把文件、路径和 URL 拖到全局投放区进行优化"',
    r'"\nCompression factors above 80% drop every 4th, 3rd or 2nd frame of animated GIFs. The animation can either play faster with the remaining frames, or keep its duration by showing each frame longer"': r'"\n压缩系数高于 80% 时,动图 GIF 会每 4、3 或 2 帧丢 1 帧:可让动画用剩余帧播得更快,也可保持时长、每帧显示更久"',
    r'"\nCopied image data (e.g. screenshots)"': r'"\n拷贝的图像数据(如截屏)"',
    r'"\nCopy files resulting from drop zone or file watch optimisation\nso they can be pasted right after optimisation ends"': r'"\n复制投放区或文件夹监视优化产生的文件,\n优化结束后即可直接粘贴"',
    r'"\nCopying images from Finder results in file paths instead of image data"': r'"\n从访达拷贝图像时,得到的是文件路径而非图像数据"',
    r'"\nDeleted identifiable metadata from files (e.g. camera that took the photo, location, date and time etc.)"': r'"\n删除文件中可识别的元数据(如拍摄设备、位置、日期时间等)"',
    r'"\nDropping many files at once (or a folder with many files) opens a single batch window that optimises them all efficiently. Originals are backed up first and can be restored."': r'"\n一次拖入大量文件(或含大量文件的文件夹)会打开一个批量窗口统一高效优化。原件会先备份,可随时恢复。"',
    r'"\nEach new optimised image is added to a file list in the clipboard, so you can paste them all at once into image editor apps like Pixelmator or Affinity, or into notes"': r'"\n每张新优化的图像都会加入剪贴板中的文件列表,可在 Pixelmator、Affinity 等图像编辑器或笔记里一次性全部粘贴"',
    r'"\nFormats that many apps cannot open well are converted to a widely supported one automatically before optimising."': r'"\n许多应用难以打开的格式会先自动转换为支持广泛的格式再优化。"',
    r'"\nHide drop zone by default to avoid distractions while dragging files, show it by manually pressing ⌥ Option once"': r'"\n默认隐藏投放区,拖文件时不打扰;按一次 ⌥ Option 手动显示"',
    r'"\nIncrease if files on iCloud Drive get optimised twice"': r'"\n如果 iCloud Drive 上的文件被重复优化,调大此项"',
    r'"\nKeep color profile metadata tags untouched when stripping EXIF metadata"': r'"\n去除 EXIF 元数据时不改动色彩配置标签"',
    r'"\nOptimise copied PDF file paths"': r'"\n优化拷贝的 PDF 文件路径"',
    r'"\nOptimise copied audio file paths"': r'"\n优化拷贝的音频文件路径"',
    r'"\nOptimise copied video file paths"': r'"\n优化拷贝的视频文件路径"',
    r'"\nRename the file using this template before copying the path to the clipboard"': r'"\n复制路径到剪贴板前,按此模板重命名文件"',
    r'"\nScales down images taken on HiDPI screens to the standard DPI for web (e.g. Retina to 1x)"': r'"\n把 HiDPI 屏幕拍摄的图像缩到网页标准 DPI(如 Retina 降到 1x)"',
    r'"\nShow each clipboard optimisation as a separate result instead of replacing the previous one"': r'"\n每次剪贴板优化都单独显示一个结果,而非替换上一个"',
    r'"\nThe optimised file will have the same creation and modification dates as the original file"': r'"\n优化后的文件将保留与原件相同的创建和修改时间"',
    r'"\nUsing scripts in pipelines allows for flexible operations but can be dangerous if not properly verified"': r'"\n在管线中使用脚本很灵活,但未经核实可能有风险"',
    r'"\nUsually from graphical design apps, sometimes better left alone"': r'"\n通常来自设计类应用,有时保持原样更好"',
    r'"\nWatch for copied data and optimise it automatically"': r'"\n监视拷贝的数据并自动优化"',
    r'"\nWhen copying optimised image data, also copy the path of the image file"': r'"\n拷贝优化后的图像数据时,同时复制图像文件路径"',
    r'"\nWhen you pick a new format by clicking the file extension on a floating result, or via the submenu **Convert to...** in the right-click menu."': r'"\n通过点按悬浮结果上的扩展名,或右键菜单中的 **转换为...** 子菜单选择新格式。"',
    r'"\nWhere the smaller file is saved, and whether it replaces the original"': r'"\n较小的文件保存到哪里,以及是否替换原件"',
    r'"\n\nBy default, the layout switches to compact automatically when there are more than 5 results on the screen"': r'"\n\n默认情况下,屏幕上结果超过 5 个时自动切换为紧凑布局"',
    r'"\n\nDisabling this will make Clop run in an UI-less mode, but keep optimising files in the background. Drop zone can be disabled separately in the Drop zone tab"': r'"\n\n关闭后 Clop 将以无界面模式运行,但仍会在后台优化文件。投放区可在「投放区」标签页单独关闭"',
    r'"\n\nDon\'t show the action name labels that pop up while hovering result buttons"': r'"\n\n悬停结果按钮上时不弹出操作名称标签"',
    r'"\n\nWhen the cursor stays on another screen for a couple of seconds, move the results to that screen"': r'"\n\n光标在另一块屏幕停留几秒后,结果会自动移过去"',
    r'"^: show preset zones"': r'"^:显示预设区"',
    r'"becomes"': r'"变为"',
    r'"but no less than"': r'"但不低于"',
    r'"by"': r'"按"',
    r'"files after"': r'"个文件后"',
    r'"files"': r'"个文件"',
    r'"format bar at the bottom"': r'"底部格式栏"',
    r'"height"': r'"高度"',
    r'"hold"': r'"按住"',
    r'"hover on the file extension"': r'"悬停在扩展名上"',
    r'"longest edge"': r'"最长边"',
    r'"never clean up"': r'"从不清理"',
    r'"never"': r'"从不"',
    r'"of inactivity"': r'"无操作后"',
    r'"only for preview"': r'"仅用于预览"',
    r'"press a number to downscale to"': r'"按数字键缩放到"',
    r'"same as non-clipboard"': r'"与常规优化相同"',
    r'"upload to Dropshare"': r'"上传到 Dropshare"',
    r'"width"': r'"宽度"',
    r'"·  drop to add more, select and ⌫ to remove files"': r'"· 拖入可继续添加,选中后按 ⌫ 移除"',
    r'"⌘: use aggressive optimisation"': r'"⌘:使用激进优化"',
    r'"⌥ click keeps both formats"': r'"⌥ 点按保留两种格式"',
    r'"clipboard after"': r'"剪贴板新内容后"',
    r'"drag and drop outside"': r'"拖到外部时"',
}
