# -*- coding: utf-8 -*-
# Clop 快速汉化 · 第 3 批(title: / help: / details: 参数文案)
T3 = {
    r'"A script step runs arbitrary code. Off means Clop refuses a pipeline from an agent that contains one, and names the step. Scripts you write yourself are unaffected"': r'"脚本步骤会执行任意代码。关闭时,Clop 会拒绝包含脚本步骤的智能体管线并指出该步骤;你自己编写的脚本不受影响"',
    r'"Accept changes from agents"': r'"接受智能体的修改"',
    r'"Accumulation timeout"': r'"累积超时"',
    r'"Action keys"': r'"操作键"',
    r'"Allow agents to write script steps"': r'"允许智能体写入脚本步骤"',
    r'"Allows dragging files, paths and URLs to a global drop zone for optimisation"': r'"允许把文件、路径和 URL 拖到全局投放区进行优化"',
    r'"Animated GIF"': r'"动图 GIF"',
    r'"Audio bitrate (kbps)"': r'"音频码率(kbps)"',
    r'"Auto clear all compact results after"': r'"紧凑结果全部清空时间"',
    r'"Auto hide clipboard results after"': r'"剪贴板结果自动隐藏时间"',
    r'"Auto hide file results after"': r'"文件结果自动隐藏时间"',
    r'"Auto hide floating results"': r'"自动隐藏悬浮结果"',
    r'"Automatically run actions on files after (or before) optimisation: convert, crop, copy, rename and more\\nType an action name and press Tab to fill in, Enter to finish"': r'"在优化后(或前)自动对文件执行操作:转换、裁剪、复制、重命名等\\n输入操作名后按 Tab 补全,按 Enter 完成"',
    r'"Batch mode file threshold"': r'"批量模式文件数阈值"',
    r'"Batch mode"': r'"批量模式"',
    r'"By default, the layout switches to compact automatically when there are more than 5 results on the screen"': r'"默认情况下,屏幕上结果超过 5 个时自动切换为紧凑布局"',
    r'"Click a zone to assign or create a pipeline. Drag files onto a zone to run its actions."': r'"点按预设区可指派或新建管线;把文件拖到预设区即运行其操作。"',
    r'"Clipboard"': r'"剪贴板"',
    r'"Clop automatically picks a per-PDF DPI from the source image density and downscales images above it"': r'"Clop 按源图像密度自动为每个 PDF 选择 DPI,并缩小超过它的图像"',
    r'"Command line"': r'"命令行"',
    r'"Compact layout"': r'"紧凑布局"',
    r'"Compression factors above 80% drop every 4th, 3rd or 2nd frame of animated GIFs. The animation can either play faster with the remaining frames, or keep its duration by showing each frame longer"': r'"压缩系数高于 80% 时,动图 GIF 会每 4、3 或 2 帧丢 1 帧:可让动画用剩余帧播得更快,也可保持时长、每帧显示更久"',
    r'"Convert any audio file to MP3"': r'"将任意音频文件转换为 MP3"',
    r'"Convert images to the compact WebP format"': r'"将图像转换为紧凑的 WebP 格式"',
    r'"Convert less compatible formats to AAC or MP3 before optimisation; anything not picked keeps its own format"': r'"优化前把兼容性差的格式转换为 AAC 或 MP3;未勾选的格式保持原样"',
    r'"Convert to AAC (M4A)"': r'"转换为 AAC(M4A)"',
    r'"Convert to MP3"': r'"转换为 MP3"',
    r'"Convert to jpeg"': r'"转换为 jpeg"',
    r'"Convert to mp4"': r'"转换为 mp4"',
    r'"Convert to png"': r'"转换为 png"',
    r'"Converted audio name template"': r'"转换后音频的命名模板"',
    r'"Converted audio path template"': r'"转换后音频的路径模板"',
    r'"Converted file name template for Same folder as original"': r'"「与原件同文件夹」时转换后文件的命名模板"',
    r'"Converted file path template for Specific folder"': r'"「指定文件夹」时转换后文件的路径模板"',
    r'"Converts less known formats to more compatible ones before optimisation"': r'"优化前把小众格式转换为更兼容的格式"',
    r'"Copy files resulting from drop zone or file watch optimisation so they can be pasted right after optimisation ends"': r'"复制投放区或文件夹监视优化产生的文件,优化结束后即可直接粘贴"',
    r'"Copying images from Finder results in file paths instead of image data"': r'"从访达拷贝图像时,得到的是文件路径而非图像数据"',
    r'"Crop pages based on their longest edge"': r'"按最长边裁剪页面"',
    r'"Crop to 800px and convert to an animated GIF"': r'"裁剪到 800px 并转为动图 GIF"',
    r'"Default link expiration"': r'"默认链接有效期"',
    r'"Delete original image"': r'"删除原始图像"',
    r'"Deleted identifiable metadata from files (e.g. camera that took the photo, location, date and time etc.)"': r'"删除文件中可识别的元数据(如拍摄设备、位置、日期时间等)"',
    r'"Device"': r'"设备"',
    r'"Disabling this will make Clop run in an UI-less mode, but keep optimising files in the background. Drop zone can be disabled separately in the Drop zone tab"': r'"关闭后 Clop 将以无界面模式运行,但仍会在后台优化文件。投放区可在「投放区」标签页单独关闭"',
    r'"Dismiss compact result on drag and drop outside"': r'"拖到外部时关闭紧凑结果"',
    r'"Dismiss compact result on upload to Dropshare"': r'"上传到 Dropshare 时关闭紧凑结果"',
    r'"Dismiss result on drag and drop outside"': r'"拖到外部时关闭结果"',
    r'"Dismiss result on upload to Dropshare"': r'"上传到 Dropshare 时关闭结果"',
    "\"Don't show the action name labels that pop up while hovering result buttons\"": "\"悬停结果按钮上时不显示操作名称标签\"",
    r'"Double the playback speed and remove the audio"': r'"双倍速播放并移除音轨"',
    r'"Downscale factor"': r'"缩放系数"',
    r'"Drag all results"': r'"拖动全部结果"',
    r'"Drag all selected files"': r'"拖动全部所选文件"',
    r'"Drag all"': r'"拖动全部"',
    r'"Drag files, paths and URLs onto a global zone to optimise them"': r'"把文件、路径和 URL 拖到全局投放区即可优化"',
    r'"Drop zone"': r'"投放区"',
    r'"Dropping many files at once (or a folder with many files) opens a single batch window that optimises them all efficiently. Originals are backed up first and can be restored."': r'"一次拖入大量文件(或含大量文件的文件夹)会打开一个批量窗口统一高效优化;原件先备份,可恢复。"',
    r'"Each new optimised image is added to a file list in the clipboard, so you can paste them all at once into image editor apps like Pixelmator or Affinity, or into notes"': r'"每张新优化的图像都会加入剪贴板的文件列表,可在 Pixelmator、Affinity 等编辑器或笔记中一次性全部粘贴"',
    r'"Edit with external app"': r'"用外部应用编辑"',
    r'"Enable **audio** auto-optimiser"': r'"启用 **音频** 自动优化"',
    r'"Enable PDF auto-optimiser"': r'"启用 PDF 自动优化"',
    r'"Enable image auto-optimiser"': r'"启用图像自动优化"',
    r'"Enable video auto-optimiser"': r'"启用视频自动优化"',
    r'"Extract each PDF page as a JPEG image"': r'"将每个 PDF 页面导出为 JPEG 图像"',
    r'"FLAC (lossless)"': r'"FLAC(无损)"',
    r'"File count"': r'"文件数量"',
    r'"File name handling"': r'"文件名处理"',
    r'"File size"': r'"文件大小"',
    r'"Force all pages to be horizontal"': r'"强制所有页面为横向"',
    r'"Force all pages to be vertical"': r'"强制所有页面为纵向"',
    r'"Formats that many apps cannot open well are converted to a widely supported one automatically before optimising."': r'"许多应用难以打开的格式会在优化前自动转换为支持广泛的格式。"',
    r'"Full layout"': r'"完整布局"',
    r'"Halve the image resolution"': r'"图像分辨率减半"',
    r'"Halve the video resolution"': r'"视频分辨率减半"',
    r'"Hand an optimised file to an editor of your choice with ⌘E or the right-click menu"': r'"按 ⌘E 或通过右键菜单把优化后的文件交给自选编辑器"',
    r'"Handle images copied from the Photos app"': r'"处理从「照片」应用拷贝的图像"',
    r'"Hardware H.265"': r'"硬件 H.265"',
    r'"Help improve Clop by sending anonymous crash and error reports to the developer"': r'"向开发者发送匿名崩溃与错误报告,帮助改进 Clop"',
    r'"Hide drop zone by default to avoid distractions while dragging files, show it by manually pressing ⌥ Option once"': r'"默认隐藏投放区,拖文件时不打扰;按一次 ⌥ Option 手动显示"',
    r'"Hide floating result"': r'"隐藏悬浮结果"',
    r'"Hold reveals them while the key is down; tap leaves them up"': r'"按住时显示,松开消失;点按则保持显示"',
    r'"How long a Send securely link stays alive"': r'"安全发送链接的存续时长"',
    r'"How long consecutive copied images keep accumulating into one file list"': r'"连续拷贝的图像在多久内累积进同一文件列表"',
    r'"How the format control on a floating result behaves"': r'"悬浮结果上格式控件的交互方式"',
    r'"How the preset zones reveal themselves over the drop zone"': r'"预设区在投放区上的呈现方式"',
    r'"Ignored apps"': r'"忽略的应用"',
    r'"Image, video, PDF or audio file"': r'"图像、视频、PDF 或音频文件"',
    r'"Increase if files on iCloud Drive get optimised twice"': r'"如果 iCloud Drive 文件被重复优化,调大此项"',
    r'"Install by hand"': r'"手动安装"',
    r'"Install in"': r'"安装到"',
    r'"Keep color profile metadata tags untouched when stripping EXIF metadata"': r'"去除 EXIF 时不改动色彩配置标签"',
    r'"Name template for Same folder as original"': r'"「与原件同文件夹」的命名模板"',
    r'"Name template for clipboard images"': r'"剪贴板图像的命名模板"',
    r'"Name template for converted videos saved in the same folder"': r'"存到同文件夹的转换视频命名模板"',
    r'"Name template for optimised videos saved in the same folder"': r'"存到同文件夹的优化视频命名模板"',
    r'"Only files within these limits are optimised"': r'"只有在此范围内的文件会被优化"',
    r'"Only optimises files between the set sizes"': r'"只优化介于设定大小之间的文件"',
    r'"Only optimises files with width and height between the set values"': r'"只优化宽高介于设定值之间的文件"',
    r'"Optimisation rules"': r'"优化规则"',
    r'"Optimisation"': r'"优化"',
    r'"Optimise PDFs as they appear in these folders"': r'"这些文件夹里出现的 PDF 会被自动优化"',
    r'"Optimise audio files as they appear in these folders"': r'"这些文件夹里出现的音频会被自动优化"',
    r'"Optimise copied PDF file paths"': r'"优化拷贝的 PDF 文件路径"',
    r'"Optimise copied audio file paths"': r'"优化拷贝的音频文件路径"',
    r'"Optimise copied video file paths"': r'"优化拷贝的视频文件路径"',
    r'"Optimise images as they appear in these folders"': r'"这些文件夹里出现的图像会被自动优化"',
    r'"Optimise screenshots and file them under ~/Pictures/Screenshots/year/month"': r'"优化截屏并归档到 ~/Pictures/Screenshots/年/月"',
    r'"Optimise videos as they appear in these folders"': r'"这些文件夹里出现的视频会被自动优化"',
    r'"Optimised audio name template"': r'"优化后音频的命名模板"',
    r'"Optimised audio path template"': r'"优化后音频的路径模板"',
    r'"Optimising files, changing settings, saving pipelines. Reading settings and pipelines stays allowed either way"': r'"允许优化文件、修改设置、保存管线;无论开关,读取设置与管线始终允许"',
    r'"Output path (or temporary folder)"': r'"输出路径(或临时文件夹)"',
    r'"Output path"': r'"输出路径"',
    r'"Overlay watermark.png from the same folder onto the image"': r'"把同文件夹的 watermark.png 叠加到图像上"',
    r'"Overlay watermark.png from the same folder onto the video"': r'"把同文件夹的 watermark.png 叠加到视频上"',
    r'"Overwrite original file"': r'"覆盖原始文件"',
    r'"PDF DPI"': r'"PDF DPI"',
    r'"PDFs"': r'"PDF 文件"',
    r'"Page layout"': r'"页面布局"',
    r'"Paper size or device"': r'"纸张尺寸或设备"',
    r'"Paper"': r'"纸张"',
    r'"Path template for Specific folder"': r'"「指定文件夹」的路径模板"',
    r'"Path template for converted videos saved in a specific folder"': r'"存到指定文件夹的转换视频路径模板"',
    r'"Path template for optimised videos saved in a specific folder"': r'"存到指定文件夹的优化视频路径模板"',
    r'"Pattern for naming images saved from the clipboard"': r'"剪贴板图像的保存命名规则"',
    "\"Periodically delete files older than this from Clop's working directory\"": "\"定期从 Clop 工作目录删除早于此时间的文件\"",
    r'"Photos crop orientation"': r'"照片裁剪方向"',
    r'"Photos integration"': r'"「照片」集成"',
    r'"Pick the best DPI per document"': r'"按文档选择最佳 DPI"',
    r'"Pipeline type"': r'"管线类型"',
    r'"Playback speed factor"': r'"播放速度倍数"',
    r'"Preset zones"': r'"预设区"',
    r'"Privacy"': r'"隐私"',
    r'"Process a large drop in a fast native window instead of one floating result per file"': r'"大量拖入时在原生窗口中快速处理,而非每个文件一个悬浮结果"',
    "\"Re-encode a video's audio track to AAC for compatibility\"": "\"把视频音轨重编码为 AAC 以提升兼容性\"",
    r'"Remove audio from video"': r'"移除视频音轨"',
    r'"Resize keys"': r'"缩放键"',
    r'"Resize over long edge"': r'"按最长边缩放"',
    r'"Reusable pipelines available in automation, preset zones and right-click menus"': r'"可在自动化、预设区和右键菜单中复用的管线"',
    r'"Run actions on every file you copy"': r'"对拷贝的每个文件自动执行操作"',
    r'"Run actions on files dropped here: convert, crop, copy, rename and more"': r'"对拖到这里 的文件执行操作:转换、裁剪、复制、重命名等"',
    r'"SVT-AV1 in MKV"': r'"SVT-AV1(MKV)"',
    r'"Same folder name template"': r'"同文件夹命名模板"',
    r'"Saved Pipelines"': r'"已保存的管线"',
    r'"Scale video to 1920px wide and optimise"': r'"视频缩放到 1920px 宽并优化"',
    r'"Seconds before a clipboard result disappears"': r'"剪贴板结果消失前的秒数"',
    r'"Seconds before a file result disappears"': r'"文件结果消失前的秒数"',
    r'"Seconds before every compact result is cleared"': r'"全部紧凑结果清空前的秒数"',
    r'"Send error reports"': r'"发送错误报告"',
    r'"Server"': r'"服务器"',
    r'"Show Copy all and Clear all buttons"': r'"显示「全部复制」和「全部清空」按钮"',
    r'"Show converted image as result"': r'"结果显示为转换后的图像"',
    r'"Show each clipboard optimisation as a separate result instead of replacing the previous one"': r'"每次剪贴板优化单独显示一个结果,而非替换上一个"',
    r'"Show images in compact results"': r'"紧凑结果中显示图像"',
    r'"Show preset zones by holding or tapping Control"': r'"按住或点按 Control 键显示预设区"',
    r'"Showing preset zones"': r'"预设区显示方式"',
    r'"Side actions"': r'"侧边操作"',
    r'"Size or aspect ratio toggle"': r'"尺寸/宽高比切换"',
    r'"Size"': r'"大小"',
    r'"Skip clipboard optimisation while one of these apps is in front"': r'"这些应用在前台时跳过剪贴板优化"',
    r'"Skips optimisation when more than this many PDFs are copied or moved at once"': r'"一次拷贝/移动的 PDF 超过此数量时跳过优化"',
    r'"Skips optimisation when more than this many videos are copied or moved at once"': r'"一次拷贝/移动的视频超过此数量时跳过优化"',
    r'"Software H.265"': r'"软件 H.265"',
    r'"Specific folder name template"': r'"指定文件夹命名模板"',
    r'"Steps"': r'"步骤"',
    r'"The optimised file will have the same creation and modification dates as the original file"': r'"优化后的文件保留与原件相同的创建和修改时间"',
    r'"Trigger keys"': r'"触发键"',
    r'"Use a name template for clipboard images"': r'"为剪贴板图像使用命名模板"',
    r'"Use aggressive optimisation"': r'"使用激进优化"',
    r'"Usually from graphical design apps, sometimes better left alone"': r'"通常来自设计类应用,有时保持原样更好"',
    r'"Video, image or PDF file"': r'"视频、图像或 PDF 文件"',
    r'"Video, image or audio file"': r'"视频、图像或音频文件"',
    r'"Video, image, PDF or audio file"': r'"视频、图像、PDF 或音频文件"',
    r'"WAV (uncompressed)"': r'"WAV(未压缩)"',
    r'"WAV, AIFF and FLAC are lossless, so the compression factor does not apply to them."': r'"WAV、AIFF 和 FLAC 是无损格式,压缩系数对它们不生效。"',
    r'"Watch for copied data and optimise it automatically"': r'"监视拷贝的数据并自动优化"',
    r'"Watch paths"': r'"监视路径"',
    r'"Watched file filters"': r'"监视文件过滤"',
    r'"When copying optimised image data, also copy the path of the image file"': r'"拷贝优化后的图像数据时,同时复制图像文件路径"',
    r'"When the cursor stays on another screen for a couple of seconds, move the results to that screen"': r'"光标在另一块屏幕停留几秒后,结果会自动移过去"',
    r'"When you pick a new format by clicking the file extension on a floating result, or via the submenu **Convert to...** in the right-click menu."': r'"通过点按悬浮结果上的扩展名,或右键菜单中的 **转换为...** 子菜单选择新格式。"',
    r'"Where temporary files and backups are stored and where the optimised files are saved"': r'"临时文件、备份与优化后文件的存放位置"',
    r'"Where the smaller file is saved, and whether it replaces the original"': r'"较小的文件保存到哪里,以及是否替换原件"',
    r'"Whether changing speed drops frames or re-times them"': r'"变速时是丢帧还是重新计时"',
    r'"Which corner floating results appear in"': r'"悬浮结果出现在哪个角落"',
    r'"Which way to crop images coming from Photos.app"': r'"来自「照片」应用的图像裁剪方式"',
    r'"Working directory cleanup"': r'"工作目录清理"',
    r'"Working directory path"': r'"工作目录路径"',
    r'"You can choose multiple pipelines, one per type, so the button adapts per file"': r'"可选多条管线(每种类型一条),按钮按文件类型自适应"',
}
